framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
                loco:
                    dsn: '%env(LOCO_DSN)%'
                    domains: ['messages']
                    locales: [:at, :de, :ch_de, :ch_fr, :fr, :int_en, :int_fr]
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
